version: "3.9"

services:
  proxy:
    image: caddy:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - proxy
    depends_on:
      - app
  app:
    image: spotify-ranker
    build: {}
    environment:
      DATABASE_URL: "sqlite:////data/app.db"
    volumes:
      - ../data:/data
    networks:
      - proxy

networks:
  proxy:
