# fly.toml app configuration file generated for songranker on 2023-07-18T23:04:42-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "songranker"
primary_region = "yyz"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "5000"
  FLASK_APP = "main.py"
  LOG_TO_STDOUT = "1"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
