# fly.toml app configuration file generated for songraker on 2023-07-18T16:24:02-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "songraker"
primary_region = "yyz"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[build]
  dockerfile = "Dockerfile"
  ignorefile = ".dockerignore"
