"""rounds and album score

Revision ID: 9fe193810951
Revises: 1b2f7aba0c3f
Create Date: 2021-11-10 15:58:58.499939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fe193810951'
down_revision = '1b2f7aba0c3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('score', sa.Integer(), nullable=True))
    op.add_column('artist', sa.Column('rounds', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('rounds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'rounds')
    op.drop_column('artist', 'rounds')
    op.drop_column('album', 'score')
    # ### end Alembic commands ###
